Removed Sold Cow Toast
ucsb-cs156-f23/proj-happycows-f23-5pm-1 pull request #17
Opened 2023-11-17 22:57 UTC by Yashasvi-Vangala

## Overview

In this PR, I have removed the toast message and the associated toast tests when a cow is sold. This features improves clarity for users by removing distracting toasts like "cow sold" when the change is clearly visible in the cows owned value. 
## Gif (Optional)
![No Toast PR ](https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/assets/55556296/3dd24542-496a-473a-bb16-817e880e9f27)

## Validation (Optional)

Deployed at
1. Clone this repo and checkout yv-no-purchase-toast.
2. run `mvn spring-boot:run`
3. In another terminal, execute `cd /frontend; npm install; npm start`
4. Create a commons, join the commons and go the playpage.
5. This buying and sellling cows

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #3

2023-11-20 07:53 UTC, pingyujc reviewed
Passed all the tests.

Code looks good to me!

2023-11-20 20:41 UTC, pconrad requested changes
We should probably remove commented out code.

Other than that, LGTM, but we should probably fix that before we merge.

2023-11-20 20:41 UTC, pconrad commented on frontend/src/main/pages/PlayPage.js
> +// import { toast } from "react-toastify";
I wonder why you commented out this line instead of just deleting it?

2023-11-20 21:34 UTC, Yashasvi-Vangala commented on frontend/src/main/pages/PlayPage.js
> +// import { toast } from "react-toastify";
I envisioned that I will need the toast package in the future when testing new features on `PlayPage.js`. I have removed it for this PR

2023-11-21 00:11 UTC, pconrad approved these changes
LGTM!

2023-11-21 00:11 UTC, merged