Harold ux improvements to leaderboard page 2
ucsb-cs156-f23/proj-happycows-f23-5pm-1 pull request #19
Opened 2023-11-20 13:01 UTC by haroldmo

## Overview

In this PR, the UX improvements to the leaderboard page were implemented. The "back" button is moved to the top right, the columns titled "userCommons Id" and "User Id" were removed, the column "username" was changed to "Farmer", and all the numerical fields were right justified.

## Before
![image](https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/assets/72893084/61eacaa4-f00f-4c20-8e94-78f84b7018a2)

## After
![image](https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/assets/72893084/0c31510b-66fb-4577-bffa-69c79f69ca24)

Closes #2

2023-11-21 05:09 UTC, lukewli commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
Probably will have to delete all commented code. The professor made the same comment in Yash's PR.

2023-11-22 01:36 UTC, lukewli submitted a review, later dismissed
Tests passed. Looks good.

2023-11-22 16:58 UTC, pconrad commented on frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
> +    // expect(screen.getAllByText("$1,000.00")[0]).toHaveStyle("text-align: right;");
Please see: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-22 16:58 UTC, pconrad commented on frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
> +    // expect(screen.getAllByText("$1,000.00")[0]).toHaveStyle("text-align: right;");
```suggestion
```

2023-11-22 16:59 UTC, pconrad requested changes
As @lukewli predicted, I'm asking that you remove the commented out code.

Please see also: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-22 16:59 UTC, pconrad commented on frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
> +    // expect(screen.getAllByText("$1,000.00")[0]).toHaveStyle("text-align: right;");
```suggestion
```

2023-11-22 23:39 UTC, haroldmo commented on frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
> +    // expect(screen.getAllByText("$1,000.00")[0]).toHaveStyle("text-align: right;");
I will fix that now. Thank you for catching that!

2023-11-24 21:16 UTC, pconrad approved these changes
LGTM

2023-11-25 20:09 UTC, merged