Added explanation description to the fields within the Create Commons page
ucsb-cs156-f23/proj-happycows-f23-5pm-1 pull request #21
Opened 2023-11-21 08:18 UTC by AngelG261

…mons page.

## Overview
In this PR, I added/edited an explanation description to all of the fields within the Create Commons page. This includes: Commons Name, Starting Balance, Cow Price among all the other fields.

## Screenshots (Optional)
###Before
<img width="1014" alt="Screenshot 2023-11-20 at 11 34 59 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/assets/77658947/42f18e26-36bb-4bcd-bf31-63292462e395">

###After
<img width="1085" alt="Screenshot 2023-11-21 at 12 08 40 AM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/assets/77658947/5f2a7076-9238-4933-a146-afe1a60b3283">

Closes #11

2023-11-21 23:04 UTC, Yashasvi-Vangala approved these changes, later dismissed
Deployed this on local host, feature works with no issues.
Here's the feature in action:
![CR Gif](https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/assets/55556296/2490f4cc-6f10-45f0-adc0-3309dcbf0e0a)

2023-11-22 20:26 UTC, pconrad requested changes
The changes to CommonsForm.js LGTM, but I'm wondering why the changes to package.json and package-lock.json are needed.

If these aren't necessary for this PR, you may want to revert both of these back to the code in the main branch.

2023-11-22 20:26 UTC, pconrad commented on frontend/package.json
> +    "npm": "^10.2.4",
Do we need to bump the version of npm?   If so why?

We typically don't take on extra dependencies unless there is a specific reason to do.  If there something about this particular change that makes this needed?

If it's just "a good idea in general" rather than something related to adding the tooltips to the create commons page, that might be better in a separate PR with a specific justification.
```suggestion
```

2023-11-22 20:26 UTC, pconrad commented on frontend/package.json
> +    "start": "^5.1.0",
Same comment as above.
```suggestion
```

2023-11-22 20:27 UTC, pconrad commented
> The changes to CommonsForm.js LGTM, but I'm wondering why the changes to package.json and package-lock.json are needed.
> 
> If these aren't necessary for this PR, you may want to revert both of these back to the code in the main branch.

This article explains how to revert changes to package-lock.json; the same technique can be used for package.json:

https://ucsb-cs156.github.io/topics/pull_requests/package_lock_json.html

2023-11-27 17:01 UTC, pconrad requested changes
So, you reverted the changes to package.json, which is a good start.

Now please do the same for package-lock.json

https://ucsb-cs156.github.io/topics/pull_requests/package_lock_json.html

2023-11-28 17:23 UTC, pconrad approved these changes
LGTM

2023-11-28 17:32 UTC, merged